# Generated by Django 5.1.3 on 2025-08-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developpement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='password',
        ),
    ]
